config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books

  root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :publications
  has_many :books, through: :publications
  validates :first_name, presence: true
  validates :last_name, presence: true
  def name
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :publications
  has_many :authors, through: :publications
  validates :title, presence: true
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :biography)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :isbn, :description, :publisher, :published_on, :cover_url, { author_ids: [] } )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to(name, options=nil, html_options=nil, &block)
    nav_options = {}
    nav_options.merge!(class: "active") if controller_name == name.downcase
    content_tag :li, nav_options do
      link_to name, options, html_options, &block
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-8">
      <%= f.label :biography %><br>
      <%= f.text_area :biography, class: "form-control", rows: 8 %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Author', new_author_path, class: "btn btn-primary btn-large pull-right" %>

<h1>Authors</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th class="centered">Number of books</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.name, author %></td>
        <td class="centered"><%= author.books.count %></td>
        <td class="centered">
          <%= link_to edit_author_path(author) do %>
            <span class="glyphicon glyphicon-pencil"> Edit</span>
          <% end %>
        </td>
        <td class="centered">
          <%= link_to author, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"> Destroy</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @author.name %></h2>

<p>
  <strong>Biography:</strong>
  <%= simple_format @author.biography %>
</p>

<p>
  <strong>Books:</strong>
  <% @author.books.each do |book| %>
    <%= link_to image_tag(book.cover_url, alt: book.title), book %>
  <% end %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :isbn %><br>
      <%= f.text_field :isbn, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-8">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control", rows: 8 %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :publisher %><br>
      <%= f.text_field :publisher, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-2">
      <%= f.label :published_on %><br>
      <div class="input-group date">
        <%= f.text_field :published_on, class: "form-control" %>
        <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :cover_url %><br>
      <%= f.text_field :cover_url, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-4">
      <h4>Authors</h3>
      <%= hidden_field_tag "book[author_ids][]", nil %>
      <% Author.all.each do |author| %>
        <div class="checkbox">
          <%= label_tag dom_id(author) do %>
            <%= check_box_tag "book[author_ids][]", author.id, @book.author_ids.include?(author.id), id: dom_id(author) %>
            <%= author.name %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Book', new_book_path, class: "btn btn-primary btn-large pull-right" %>

<h1>Books</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Publisher</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to image_tag(book.cover_url, alt: book.title, class: "thumbnail-sm"), book, class: "thumbnail" %>
        </td>
        <td><%= link_to book.title, book %></td>
        <td><%= book.publisher %></td>
        <td class="centered">
          <%= link_to edit_book_path(book) do %>
            <span class="glyphicon glyphicon-pencil"> Edit</span>
          <% end %>
        </td>
        <td class="centered">
          <%= link_to book, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"> Destroy</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @book.cover_url, alt: @book.title %>
</p>

<h2><%= @book.title %></h2>

<p>
  <strong><%= "Author".pluralize(@book.authors.count) %>:</strong>
  <%= @book.authors.map { |author| link_to(author.name, author) }.join(", ").html_safe %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format @book.description %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @book.published_on %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/navbar" %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#library_navbar_collapse" aria-expanded="false">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Library", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="library_navbar_collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= nav_link_to books_path do %>
          <span class="glyphicon glyphicon-book"></span> Books
        <% end %>
        <%= nav_link_to authors_path do %>
          <span class="glyphicon glyphicon-user"></span> Authors
        <% end %>
      </ul>
    </div>
  </div>
</nav>